classroom/classroom/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('seats.urls', namespace='seats')),
    path('admin/', admin.site.urls),
]

classroom/seats/urls.py
from django.urls import path

from . import views

app_name = 'seats'

urlpatterns = [
    path('', views.index, name='index'),
    path('test', views.test, name='test'),
    path('success', views.success, name='success'),
]

classroom/seats/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Student(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    # teacher = models.ForeignKey(User, on_delete=models.CASCADE,
    #                             related_name='students')

    def __str__(self):
        return f'{self.last_name} {self.first_name}'


class Arrangement(models.Model):
    number_of_columns = models.PositiveIntegerField()
    number_of_rows = models.PositiveIntegerField()
    academic_year = models.CharField(max_length=5)
    month = models.CharField(max_length=15)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE,
                                   related_name='arrangements')


class Seat(models.Model):
    column = models.PositiveIntegerField()
    row = models.PositiveIntegerField()
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True,
                                related_name='seats')
    arrangement = models.ForeignKey(Arrangement, on_delete=models.CASCADE,
                                    related_name='seats')

classroom/seats/forms.py
# from django import forms

# from .models import Arrangement, Seat, Student


# class SeatsForm(forms.Form):
#     variants = forms.IntegerField(label="Сколько вариантов?")
#     rows = forms.IntegerField(label="Сколько рядов?")
#     desks = forms.IntegerField(label="Сколько парт в ряду?")
#     pupils_lst = forms.CharField(label="Ученики")


# class SomeForm(forms.Form):
#     pupils_lst = forms.CharField(label="Ученики")


# class ArrangementForm(forms.ModelForm):
#     class Meta:
#         model = Arrangement
#         fields = ('month', 'year', 'columns', 'rows')

classroom/seats/views.py
from django.shortcuts import render
# from .forms import ArrangementForm, SomeForm


def index(request):
    template = 'seats/index.html'
    title = 'Главная страница'
    text = 'Главная страница'
    some = 'Main'
    context = {
        'title': title,
        'text': text,
        'some': some,
    }
    return render(request, template, context)

    # template = 'seats/index.html'
    # title = 'Главная страница'
    # text = 'Главная страница'
    # some = 'Card Subtitle'

    # if request.method == 'POST':
    #     arrangementform = ArrangementForm(request.POST)
    #     someform = SomeForm(request.POST)
    #     if arrangementform.is_valid():
    #         columns = arrangementform.cleaned_data['columns']
    #         rows = arrangementform.cleaned_data['rows']
    #         print('\n')
    #         print('Columns, rows: ', columns, rows)
    #         arrangementform.save()
    #     return render(request, template, {'arrangementform': arrangementform})

    # else:
    #     arrangementform = ArrangementForm()
    #     someform = SomeForm()

    # context = {
    #     'title': title,
    #     'text': text,
    #     'some': some,
    #     'arrangementform': arrangementform,
    #     'someform': someform,
    # }
    # print('КОНТЕКСТ: ', context)
    # return render(request, template, context)


def test(request):
    template = 'seats/test.html'
    title = 'Тестовая страница'
    text = 'Тестовая страница'
    some = 'Some Test'
    context = {
        'title': title,
        'text': text,
        'some': some,
    }
    return render(request, template, context)


def success(request):
    template = 'seats/success.html'
    title = 'Страница успеха'
    text = 'Страница успеха'
    some = 'Sucess'
    context = {
        'title': title,
        'text': text,
        'some': some,
    }
    return render(request, template, context)

classroom/templates/base.html
{% load static %}

<!DOCTYPE html> 
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Рассадить учеников в случайном порядке">
    <title>{% block title %}Some title...{% endblock title %}</title>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/site.webmanifest' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="/images/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    {% comment %} <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> {% endcomment %}
    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous">
  </head>  
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      {% block content %}
        Some content...
      {% endblock %}
    </main>
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

classroom/templates/includes/footer.html
Подвал

classroom/templates/includes/header.html
Верхняя часть страницы: логотип, контакты
<nav>
  Меню (навигация)
</nav>

classroom/templates/seats/index.html
{% extends 'base.html' %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block content %}
<style> {% comment%} NB! Возможно, тег не на своём месте. Проверить {% endcomment %}
  .desk {
    width: 100px;
    height: 80px;
    background-color: #8B4513;
    position: relative;
  }

  .name-inscription {
    position: absolute;
    bottom: 10px;
    left: 50%;
    transform: translateX(-50%);
    font-family: 'Arial', sans-serif;
    font-size: 16px;
    color: #FFF;
  }

  .prokhod {
    width: 40px;
    {% comment %} height: 80px; {% endcomment %}
    {% comment %} background-color: #000000; {% endcomment %}
    position: relative;
  }

  .whiteboard {
    width: 300px;
    height: 20px;
    background-color: #dddddd;
    position: relative;
  }

  table {
    border-collapse: separate;
    border-spacing: 0 20px;
  }
</style>
  <div class="card col-6">
    <h5 class="card-header">Основное содержимое страницы</h5>
    <div class="card-body">
      <h6 class="card-subtitle">{{ some }}</h6>
      <p>
        {{ text }}
      </p>
      <a href="{% url 'seats:test' %}" class="btn btn-primary">Тестовая страница</a>
      <div>
        <form method="post" action="{% url 'seats:index' %}"> 
          {% csrf_token %}
          {{ someform.as_p }}
          {{ arrangementform.as_p }}
          {% comment %} <input class="btn btn-primary" type="submit" value="Submit"> {% endcomment %}
          <button class="btn btn-primary" type="submit">Сгенерировать рассадку</button>
        </form>
      </div>

      {% comment %} {% if students %}
        {% for student in students %}
          student.name
        {% endfor %}
      {% endif %} {% endcomment %}
      
<!--      {% if seats %}
        <p>РАССАДКА 3:</p>
        <table>
          {% for element_group in transposed_list %}
            <tr>
              {% for element in element_group %}
                <td>
                  <div class="desk">
                    {% comment %} <div class="desk-top"></div> {% endcomment %}
                    <p class="name-inscription">{{ element.pupil }}</p>
                  </div>
                </td>
                {% if forloop.counter|divisibleby:variants and not forloop.last %}
                  <td>
                    <div class="prokhod">
                      {% comment %} {{ forloop.counter }} {% endcomment %}
                    </div>
                  </td>
                {% endif %}
              {% endfor %}
            </tr>
          {% endfor %}
          <tr>
            <td colspan="100%" style="text-align: center;">
              <div class="whiteboard">
                Доска
              </div>
            </td>
          </tr>
        </table>
      {% endif %}
-->
    </div>
  </div>
{% endblock %}

classroom/templates/seats/success.html
{% extends 'base.html' %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block content %}
  <div class="card col-6">
    <h5 class="card-header">ЭТО УСПЕХ!</h5>
    <div class="card-body">
      <h6 class="card-subtitle">{{ some }}</h6>
      <p>
        {{ text }}
      </p>
      <a href="{% url 'seats:index' %}" class="btn btn-primary">Вернуться на главную</a>
    </div>
  </div>
{% endblock %}

classroom/templates/seats/test.html
{% extends 'base.html' %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block content %}
  <div class="card col-6">
    <h5 class="card-header">Тестовая страница</h5>
    <div class="card-body">
      <h6 class="card-subtitle">{{ some }}</h6>
      <p>
        {{ text }}
      </p>
      <a href="{% url 'seats:index' %}" class="btn btn-primary">Вернуться на главную</a>
    </div>
  </div>
{% endblock %}